import type { CampaignPlaybook } from "@/lib/playbooks/types";

export const campaignPlaybooks: CampaignPlaybook[] = [
  {
    id: "vip_early_access",
    name: "VIP Early Access",
    type: "campaign",
    campaignType: "VIP early access",
    description: "Give high-value customers a first look at a product, collection, or launch.",
    objective: "Reward loyal customers and pull forward repeat purchases without broad discounting.",
    targetAudience: "Champions, VIPs, loyal customers, and high-CLV buyers.",
    contentSuggestions: [
      "Lead with exclusivity and gratitude.",
      "Feature the primary product or launch clearly above the fold.",
      "Use proof or scarcity only when it is true.",
      "Keep the CTA focused on early access.",
    ],
    keyMetric: "vip_repeat_purchase_revenue",
    offerRules: [
      "Default to access, status, or early visibility rather than a discount.",
      "Use private offers only when margin and brand rules allow it.",
    ],
    qaRisks: [
      "Making exclusivity claims that are not true.",
      "Over-discounting the best customers.",
      "Missing clear product context.",
    ],
    requiredData: ["customer_segment", "order_history", "product_catalog", "email_consent"],
    permissionLevel: "draft_only",
    plannerMatch: {
      campaignTypes: ["vip early access"],
      titleKeywords: ["vip", "early access", "preview"],
    },
  },
  {
    id: "product_spotlight",
    name: "Product Spotlight",
    type: "campaign",
    campaignType: "Product spotlight",
    description: "Create a focused campaign around one product or collection with a clear reason to care.",
    objective: "Drive product demand by pairing a strong product hook with a specific audience.",
    targetAudience: "Potential loyalists, category browsers, recent buyers, or product-fit segments.",
    contentSuggestions: [
      "Name the product early.",
      "Use one primary benefit and one proof point.",
      "Include product education or use cases.",
      "Avoid crowding the email with too many products.",
    ],
    keyMetric: "product_click_to_order_rate",
    offerRules: [
      "Prefer product value and proof before incentives.",
      "Use an offer only if it supports the product margin strategy.",
    ],
    qaRisks: [
      "Missing primary product.",
      "Broken product links.",
      "Vague benefits that could apply to any product.",
    ],
    requiredData: ["product_catalog", "product_url", "inventory_or_availability", "email_consent"],
    permissionLevel: "draft_only",
    plannerMatch: {
      campaignTypes: ["product spotlight"],
      titleKeywords: ["spotlight", "best-seller", "best seller"],
    },
  },
  {
    id: "at_risk_winback",
    name: "At-Risk Winback",
    type: "campaign",
    campaignType: "At-risk winback",
    description: "Re-engage customers whose purchase cadence is cooling before they lapse further.",
    objective: "Recover purchase intent from at-risk customers with a reason to return.",
    targetAudience: "At-risk, lapsed, hibernating, and can't-lose customers.",
    contentSuggestions: [
      "Acknowledge newness or helpful value without sounding punitive.",
      "Use proof, education, or product fit to rebuild interest.",
      "Keep frequency controlled for colder cohorts.",
      "Use one clear return path.",
    ],
    keyMetric: "winback_revenue_per_recipient",
    offerRules: [
      "Do not default to discounting unless promo responsiveness supports it.",
      "For no-discount plans, use newness, proof, and product value.",
    ],
    qaRisks: [
      "Spammy urgency language.",
      "Over-mailing low-engagement customers.",
      "Conflicting with deliverability warm-up policies.",
    ],
    requiredData: ["last_purchase_date", "customer_segment", "engagement_status", "email_consent"],
    permissionLevel: "draft_only",
    plannerMatch: {
      campaignTypes: ["at-risk winback"],
      titleKeywords: ["winback", "comeback", "at-risk"],
    },
  },
  {
    id: "no_discount_education",
    name: "No-Discount Education",
    type: "campaign",
    campaignType: "Educational email",
    description: "Teach product value or brand expertise without using discounts as the hook.",
    objective: "Build confidence and purchase intent while preserving margin and brand position.",
    targetAudience: "Broad engaged audiences, potential loyalists, or segments needing product confidence.",
    contentSuggestions: [
      "Lead with a useful takeaway.",
      "Connect education to one product or routine.",
      "Use proof and specificity instead of price language.",
      "Keep the CTA value-led.",
    ],
    keyMetric: "education_click_rate",
    offerRules: [
      "No discount, coupon, BOGO, sale, or markdown language.",
      "Use value, education, and proof as the conversion mechanism.",
    ],
    qaRisks: [
      "Accidental discount language.",
      "Generic educational copy with no product tie-in.",
      "Weak CTA because there is no offer.",
    ],
    requiredData: ["brand_rules", "product_catalog", "engagement_segment", "email_consent"],
    permissionLevel: "draft_only",
    plannerMatch: {
      campaignTypes: ["educational email"],
      titleKeywords: ["education", "learning", "guide"],
      requiresNoDiscount: true,
    },
  },
];
