import type { FlowPlaybook } from "@/lib/playbooks/types";

export const flowPlaybooks: FlowPlaybook[] = [
  {
    id: "welcome_series",
    name: "Welcome Series",
    type: "flow",
    trigger: "Profile joins email list or first-party subscriber source.",
    flowFilters: [
      "Has not placed order since starting flow",
      "Is not suppressed",
      "Has email consent",
    ],
    description: "Introduce the brand, build trust, and guide new subscribers toward their first purchase.",
    objective: "Convert new subscribers into first-time customers while teaching brand value and product fit.",
    targetAudience: "New email subscribers and zero-purchase profiles.",
    sequence: [
      {
        step: 1,
        name: "Brand promise",
        timing: "Immediately",
        objective: "Confirm subscription and set the brand expectation.",
        contentAngle: "Founder's note, brand story, and best entry point.",
      },
      {
        step: 2,
        name: "Product fit guide",
        timing: "1 day after step 1",
        objective: "Help the shopper choose a first product or collection.",
        contentAngle: "Best sellers, quiz-style guidance, or category education.",
      },
      {
        step: 3,
        name: "Proof and objection handling",
        timing: "2 days after step 2",
        objective: "Reduce hesitation with reviews, UGC, guarantees, or FAQs.",
        contentAngle: "Social proof plus practical reasons to buy now.",
      },
    ],
    timing: ["Immediate", "Day 1", "Day 3"],
    contentSuggestions: [
      "Use a warm welcome and plain-language brand positioning.",
      "Show best sellers or starter products early.",
      "Introduce proof before any incentive.",
    ],
    keyMetric: "first_purchase_rate",
    offerRules: [
      "Prefer education and product fit first.",
      "Use a first-purchase incentive only if brand rules allow it.",
    ],
    qaRisks: [
      "Overusing discounts before brand value is established.",
      "Sending to profiles without clear email consent.",
      "Making claims not supported by brand guidance.",
    ],
    requiredData: ["email_consent", "subscriber_created_at", "order_count", "product_catalog"],
    permissionLevel: "copilot",
  },
  {
    id: "site_abandon",
    name: "Site Abandon",
    type: "flow",
    trigger: "Known profile visits the site without viewing a product, carting, checkout, or purchase.",
    flowFilters: [
      "Has not started checkout since flow start",
      "Has not placed order since flow start",
      "Has email consent",
    ],
    description: "Recover early interest from identified visitors who leave before deeper product intent.",
    objective: "Bring known visitors back to a helpful shopping path.",
    targetAudience: "Known visitors with light site engagement and no recent purchase.",
    sequence: [
      {
        step: 1,
        name: "Helpful re-entry",
        timing: "2-4 hours after visit",
        objective: "Give the shopper a low-pressure reason to return.",
        contentAngle: "Popular categories, new arrivals, or brand point of view.",
      },
      {
        step: 2,
        name: "Guide the next click",
        timing: "1 day after step 1",
        objective: "Move the visitor toward a category or product.",
        contentAngle: "Shopping guide, best sellers, or quiz prompt.",
      },
    ],
    timing: ["2-4 hours", "Day 1"],
    contentSuggestions: [
      "Keep personalization broad because intent is still weak.",
      "Lead with discovery rather than urgency.",
      "Use brand or category hooks rather than product-specific claims.",
    ],
    keyMetric: "return_site_rate",
    offerRules: ["Avoid discounts by default for weak-intent visitors."],
    qaRisks: [
      "Treating light browsing like high purchase intent.",
      "Sending too frequently to lightly engaged profiles.",
      "Using product-specific copy when no product was viewed.",
    ],
    requiredData: ["site_visit_event", "profile_id", "email_consent", "order_count"],
    permissionLevel: "copilot",
  },
  {
    id: "browse_abandon",
    name: "Browse Abandon",
    type: "flow",
    trigger: "Known profile views a product or collection and leaves without carting or checkout.",
    flowFilters: [
      "Has not added to cart since flow start",
      "Has not started checkout since flow start",
      "Has not placed order since flow start",
      "Has email consent",
    ],
    description: "Recover product interest after a shopper views merchandise but stops short of carting.",
    objective: "Move product-aware visitors back to the product page or a related collection.",
    targetAudience: "Known browsers with product or collection views.",
    sequence: [
      {
        step: 1,
        name: "Product reminder",
        timing: "3-6 hours after browse",
        objective: "Reconnect the shopper to the viewed item or category.",
        contentAngle: "Viewed product, key benefit, and one next step.",
      },
      {
        step: 2,
        name: "Proof and alternatives",
        timing: "1 day after step 1",
        objective: "Handle hesitation and offer related options.",
        contentAngle: "Reviews, UGC, comparison, or similar products.",
      },
    ],
    timing: ["3-6 hours", "Day 1"],
    contentSuggestions: [
      "Include the viewed product when available.",
      "Use one primary CTA back to the product or collection.",
      "Add proof before escalating to offer language.",
    ],
    keyMetric: "browse_recovery_revenue",
    offerRules: [
      "Do not lead with a discount unless brand policy explicitly allows it.",
      "Prefer product proof and fit guidance.",
    ],
    qaRisks: [
      "Missing dynamic product data.",
      "Broken product links.",
      "Over-personalized language that feels invasive.",
    ],
    requiredData: ["viewed_product_event", "product_catalog", "profile_id", "email_consent"],
    permissionLevel: "copilot",
  },
  {
    id: "cart_abandon",
    name: "Cart Abandon",
    type: "flow",
    trigger: "Known profile adds item to cart and leaves before checkout or purchase.",
    flowFilters: [
      "Has not started checkout since flow start",
      "Has not placed order since flow start",
      "Has email consent",
    ],
    description: "Recover high-intent shoppers who added products to cart but did not continue.",
    objective: "Return cart abandoners to their cart and resolve purchase friction.",
    targetAudience: "Known cart abandoners with active cart contents.",
    sequence: [
      {
        step: 1,
        name: "Cart reminder",
        timing: "1-3 hours after cart event",
        objective: "Bring the shopper back while intent is fresh.",
        contentAngle: "Cart contents, simple reminder, clear CTA.",
      },
      {
        step: 2,
        name: "Trust builder",
        timing: "1 day after step 1",
        objective: "Address hesitation with proof, shipping, returns, or FAQs.",
        contentAngle: "Reviews, policy clarity, and product value.",
      },
      {
        step: 3,
        name: "Last helpful nudge",
        timing: "2 days after step 2",
        objective: "Create final urgency without over-discounting.",
        contentAngle: "Low-stock, cart expiration, or support prompt if truthful.",
      },
    ],
    timing: ["1-3 hours", "Day 1", "Day 3"],
    contentSuggestions: [
      "Show cart contents and the strongest benefit.",
      "Keep CTA singular and cart-focused.",
      "Use trust signals before incentives.",
    ],
    keyMetric: "cart_recovery_revenue",
    offerRules: [
      "Avoid automatic discounting in step 1.",
      "Only use incentives where brand rules permit and margin supports it.",
    ],
    qaRisks: [
      "Stale cart links.",
      "Incorrect product images or pricing.",
      "Untrue urgency claims.",
    ],
    requiredData: ["added_to_cart_event", "cart_url", "cart_items", "email_consent"],
    permissionLevel: "copilot",
  },
  {
    id: "checkout_abandon",
    name: "Checkout Abandon",
    type: "flow",
    trigger: "Known profile starts checkout and leaves without purchase.",
    flowFilters: [
      "Has not placed order since flow start",
      "Has email consent",
      "Suppress if checkout completed in another session",
    ],
    description: "Recover the highest-intent abandoners with checkout-specific reminders and friction removal.",
    objective: "Return shoppers to checkout and remove final purchase barriers.",
    targetAudience: "Checkout starters who did not complete purchase.",
    sequence: [
      {
        step: 1,
        name: "Checkout reminder",
        timing: "30-90 minutes after checkout start",
        objective: "Bring the shopper back before intent fades.",
        contentAngle: "Checkout resume link and concise reassurance.",
      },
      {
        step: 2,
        name: "Friction remover",
        timing: "12-24 hours after step 1",
        objective: "Address shipping, returns, payment, or product confidence.",
        contentAngle: "Policies, support, and confidence proof.",
      },
      {
        step: 3,
        name: "Final reminder",
        timing: "1-2 days after step 2",
        objective: "Give a final reason to complete purchase.",
        contentAngle: "Cart value, product benefits, and one checkout CTA.",
      },
    ],
    timing: ["30-90 minutes", "12-24 hours", "Day 2-3"],
    contentSuggestions: [
      "Use checkout resume links where possible.",
      "Prioritize clarity and trust over discovery.",
      "Keep copy short because intent is already high.",
    ],
    keyMetric: "checkout_recovery_revenue",
    offerRules: [
      "Escalate incentives carefully and only after non-discount reminders.",
      "Respect margin and brand discount policy.",
    ],
    qaRisks: [
      "Broken checkout links.",
      "Conflicting offer terms.",
      "Sending after purchase due to delayed event sync.",
    ],
    requiredData: ["started_checkout_event", "checkout_url", "checkout_items", "email_consent"],
    permissionLevel: "copilot",
  },
  {
    id: "replenishment",
    name: "Replenishment",
    type: "flow",
    trigger: "Customer is approaching expected product replenishment window.",
    flowFilters: [
      "Has purchased replenishable product",
      "Has not repurchased same product recently",
      "Has email consent",
    ],
    description: "Prompt customers to restock when timing and product cadence suggest real need.",
    objective: "Increase repeat purchase by reaching customers before they run out or switch.",
    targetAudience: "Previous buyers of replenishable products.",
    sequence: [
      {
        step: 1,
        name: "Restock reminder",
        timing: "5-10 days before expected runout",
        objective: "Create a timely restock prompt.",
        contentAngle: "Product cadence, benefit reminder, and easy reorder CTA.",
      },
      {
        step: 2,
        name: "Routine support",
        timing: "3-5 days after step 1",
        objective: "Help the customer stay consistent.",
        contentAngle: "Usage tips, routine education, and reorder CTA.",
      },
    ],
    timing: ["Before expected runout", "3-5 days later"],
    contentSuggestions: [
      "Use product-specific replenishment timing.",
      "Frame as helpful continuity, not pressure.",
      "Include reorder path and product benefit reminder.",
    ],
    keyMetric: "replenishment_repeat_rate",
    offerRules: [
      "Prefer convenience and timing over discounts.",
      "Use subscription or bundle nudges where available.",
    ],
    qaRisks: [
      "Incorrect replenishment window.",
      "Recommending restock after a recent purchase.",
      "Missing product-specific usage context.",
    ],
    requiredData: ["order_history", "product_replenishment_days", "last_purchase_date", "email_consent"],
    permissionLevel: "copilot",
  },
  {
    id: "winback",
    name: "Winback",
    type: "flow",
    trigger: "Customer passes expected repeat-purchase window or becomes at-risk/lapsed.",
    flowFilters: [
      "Has placed at least one prior order",
      "Has not placed order recently",
      "Has email consent",
      "Exclude active cart or checkout abandoners",
    ],
    description: "Re-engage lapsed or at-risk customers with value, proof, and a clear reason to return.",
    objective: "Recover customers before or after lapse without damaging deliverability or margin.",
    targetAudience: "At-risk, lapsed, or can't-lose customers.",
    sequence: [
      {
        step: 1,
        name: "Value reminder",
        timing: "At lapse threshold",
        objective: "Remind customers why they bought before.",
        contentAngle: "Product value, newness, best sellers, or routine support.",
      },
      {
        step: 2,
        name: "New reason to return",
        timing: "5-7 days after step 1",
        objective: "Create a current hook without relying only on price.",
        contentAngle: "New product, customer story, or improved experience.",
      },
      {
        step: 3,
        name: "Final reactivation",
        timing: "7-10 days after step 2",
        objective: "Make one final, controlled reactivation attempt.",
        contentAngle: "Best offer if allowed, preference center, or stay-in-touch CTA.",
      },
    ],
    timing: ["At lapse threshold", "5-7 days later", "7-10 days later"],
    contentSuggestions: [
      "Segment by value and engagement before volume ramping.",
      "Use product value and newness before incentives.",
      "Keep frequency controlled for colder cohorts.",
    ],
    keyMetric: "reactivation_revenue",
    offerRules: [
      "Use incentives only for segments where promo responsiveness or margin supports it.",
      "Avoid sending aggressive offers to refund-prone or cold profiles.",
    ],
    qaRisks: [
      "Over-mailing cold cohorts.",
      "Spammy urgency language.",
      "Discounting customers who would return without an offer.",
    ],
    requiredData: ["order_history", "last_purchase_date", "customer_segment", "email_consent"],
    permissionLevel: "copilot",
  },
];
