import type { FlowPlaybook } from "@/lib/playbooks/types";

export const CORE_REQUIRED_FLOW_PLAYBOOK_IDS = [
  "welcome_series",
  "site_abandon",
  "browse_abandon",
  "cart_abandon",
  "checkout_abandon",
  "winback",
] as const;

export const flowPlaybooks: FlowPlaybook[] = [
  {
    id: "welcome_series",
    name: "Welcome Series",
    type: "flow",
    category: "core",
    detailLevel: "full",
    priorityDefault: "high",
    trigger: "Profile joins email list or first-party subscriber source.",
    flowFilters: [
      "Has not placed order since starting flow",
      "Is not suppressed",
      "Has email consent",
    ],
    description: "Introduce the brand, build trust, and guide new subscribers toward their first purchase.",
    objective: "Convert new subscribers into first-time customers while teaching brand value and product fit.",
    targetAudience: "New email subscribers and zero-purchase profiles.",
    sequence: [
      {
        step: 1,
        name: "Brand promise",
        timing: "Immediately",
        objective: "Confirm subscription and set the brand expectation.",
        contentAngle: "Founder's note, brand story, and best entry point.",
      },
      {
        step: 2,
        name: "Product fit guide",
        timing: "1 day after step 1",
        objective: "Help the shopper choose a first product or collection.",
        contentAngle: "Best sellers, quiz-style guidance, or category education.",
      },
      {
        step: 3,
        name: "Proof and objection handling",
        timing: "2 days after step 2",
        objective: "Reduce hesitation with reviews, UGC, guarantees, or FAQs.",
        contentAngle: "Social proof plus practical reasons to buy now.",
      },
    ],
    timing: ["Immediate", "Day 1", "Day 3"],
    contentSuggestions: [
      "Use a warm welcome and plain-language brand positioning.",
      "Show best sellers or starter products early.",
      "Introduce proof before any incentive.",
    ],
    keyMetric: "first_purchase_rate",
    offerRules: [
      "Prefer education and product fit first.",
      "Use a first-purchase incentive only if brand rules allow it.",
    ],
    qaRisks: [
      "Overusing discounts before brand value is established.",
      "Sending to profiles without clear email consent.",
      "Making claims not supported by brand guidance.",
    ],
    requiredData: ["email_consent", "subscriber_created_at", "order_count", "product_catalog"],
    permissionLevel: "copilot",
    recommendedWhen: [
      "The brand captures email or SMS subscribers.",
      "First-purchase conversion from new subscribers matters.",
    ],
    conditionalRequirements: ["Email consent and subscriber source events must be available."],
    plannerMatch: {
      aliases: ["welcome", "welcome series", "new subscriber", "newsletter welcome", "subscriber onboarding"],
      triggerKeywords: ["subscribed to list", "joins list", "newsletter", "signup", "sign up"],
    },
  },
  {
    id: "site_abandon",
    name: "Site Abandon",
    type: "flow",
    category: "core",
    detailLevel: "full",
    priorityDefault: "medium",
    trigger: "Known profile visits the site without viewing a product, carting, checkout, or purchase.",
    flowFilters: [
      "Has not started checkout since flow start",
      "Has not placed order since flow start",
      "Has email consent",
    ],
    description: "Recover early interest from identified visitors who leave before deeper product intent.",
    objective: "Bring known visitors back to a helpful shopping path.",
    targetAudience: "Known visitors with light site engagement and no recent purchase.",
    sequence: [
      {
        step: 1,
        name: "Helpful re-entry",
        timing: "2-4 hours after visit",
        objective: "Give the shopper a low-pressure reason to return.",
        contentAngle: "Popular categories, new arrivals, or brand point of view.",
      },
      {
        step: 2,
        name: "Guide the next click",
        timing: "1 day after step 1",
        objective: "Move the visitor toward a category or product.",
        contentAngle: "Shopping guide, best sellers, or quiz prompt.",
      },
    ],
    timing: ["2-4 hours", "Day 1"],
    contentSuggestions: [
      "Keep personalization broad because intent is still weak.",
      "Lead with discovery rather than urgency.",
      "Use brand or category hooks rather than product-specific claims.",
    ],
    keyMetric: "return_site_rate",
    offerRules: ["Avoid discounts by default for weak-intent visitors."],
    qaRisks: [
      "Treating light browsing like high purchase intent.",
      "Sending too frequently to lightly engaged profiles.",
      "Using product-specific copy when no product was viewed.",
    ],
    requiredData: ["site_visit_event", "profile_id", "email_consent", "order_count"],
    permissionLevel: "copilot",
    recommendedWhen: [
      "Identified visitors leave before product intent is clear.",
      "The brand has enough known site traffic to justify light-intent recovery.",
    ],
    conditionalRequirements: ["Active-on-site or equivalent site visit event must be reliable."],
    plannerMatch: {
      aliases: ["site abandon", "site abandonment", "active on site", "website abandon", "site visit recovery"],
      triggerKeywords: ["active on site", "site visit", "visited site", "visited website"],
    },
  },
  {
    id: "browse_abandon",
    name: "Browse Abandon",
    type: "flow",
    category: "core",
    detailLevel: "full",
    priorityDefault: "medium",
    trigger: "Known profile views a product or collection and leaves without carting or checkout.",
    flowFilters: [
      "Has not added to cart since flow start",
      "Has not started checkout since flow start",
      "Has not placed order since flow start",
      "Has email consent",
    ],
    description: "Recover product interest after a shopper views merchandise but stops short of carting.",
    objective: "Move product-aware visitors back to the product page or a related collection.",
    targetAudience: "Known browsers with product or collection views.",
    sequence: [
      {
        step: 1,
        name: "Product reminder",
        timing: "3-6 hours after browse",
        objective: "Reconnect the shopper to the viewed item or category.",
        contentAngle: "Viewed product, key benefit, and one next step.",
      },
      {
        step: 2,
        name: "Proof and alternatives",
        timing: "1 day after step 1",
        objective: "Handle hesitation and offer related options.",
        contentAngle: "Reviews, UGC, comparison, or similar products.",
      },
    ],
    timing: ["3-6 hours", "Day 1"],
    contentSuggestions: [
      "Include the viewed product when available.",
      "Use one primary CTA back to the product or collection.",
      "Add proof before escalating to offer language.",
    ],
    keyMetric: "browse_recovery_revenue",
    offerRules: [
      "Do not lead with a discount unless brand policy explicitly allows it.",
      "Prefer product proof and fit guidance.",
    ],
    qaRisks: [
      "Missing dynamic product data.",
      "Broken product links.",
      "Over-personalized language that feels invasive.",
    ],
    requiredData: ["viewed_product_event", "product_catalog", "profile_id", "email_consent"],
    permissionLevel: "copilot",
    recommendedWhen: [
      "Product detail page views are a meaningful buying signal.",
      "Viewed product or collection events sync into Klaviyo.",
    ],
    conditionalRequirements: ["Viewed Product or comparable browse event must be present."],
    plannerMatch: {
      aliases: ["browse abandon", "browse abandonment", "product browse recovery", "viewed product recovery"],
      triggerKeywords: ["viewed product", "product viewed", "viewed item", "viewed collection"],
    },
  },
  {
    id: "cart_abandon",
    name: "Cart Abandon",
    type: "flow",
    category: "core",
    detailLevel: "full",
    priorityDefault: "high",
    trigger: "Known profile adds item to cart and leaves before checkout or purchase.",
    flowFilters: [
      "Has not started checkout since flow start",
      "Has not placed order since flow start",
      "Has email consent",
    ],
    description: "Recover high-intent shoppers who added products to cart but did not continue.",
    objective: "Return cart abandoners to their cart and resolve purchase friction.",
    targetAudience: "Known cart abandoners with active cart contents.",
    sequence: [
      {
        step: 1,
        name: "Cart reminder",
        timing: "1-3 hours after cart event",
        objective: "Bring the shopper back while intent is fresh.",
        contentAngle: "Cart contents, simple reminder, clear CTA.",
      },
      {
        step: 2,
        name: "Trust builder",
        timing: "1 day after step 1",
        objective: "Address hesitation with proof, shipping, returns, or FAQs.",
        contentAngle: "Reviews, policy clarity, and product value.",
      },
      {
        step: 3,
        name: "Last helpful nudge",
        timing: "2 days after step 2",
        objective: "Create final urgency without over-discounting.",
        contentAngle: "Low-stock, cart expiration, or support prompt if truthful.",
      },
    ],
    timing: ["1-3 hours", "Day 1", "Day 3"],
    contentSuggestions: [
      "Show cart contents and the strongest benefit.",
      "Keep CTA singular and cart-focused.",
      "Use trust signals before incentives.",
    ],
    keyMetric: "cart_recovery_revenue",
    offerRules: [
      "Avoid automatic discounting in step 1.",
      "Only use incentives where brand rules permit and margin supports it.",
    ],
    qaRisks: [
      "Stale cart links.",
      "Incorrect product images or pricing.",
      "Untrue urgency claims.",
    ],
    requiredData: ["added_to_cart_event", "cart_url", "cart_items", "email_consent"],
    permissionLevel: "copilot",
    recommendedWhen: [
      "Add-to-cart is available and cart abandonment is materially sized.",
      "The brand can safely render dynamic cart contents or a cart return path.",
    ],
    conditionalRequirements: ["Added to Cart and cart URL data must be reliable."],
    plannerMatch: {
      aliases: ["cart abandon", "cart abandonment", "abandoned cart", "cart reminder", "cart recovery"],
      triggerKeywords: ["added to cart", "add to cart", "carted item", "cart started"],
    },
  },
  {
    id: "checkout_abandon",
    name: "Checkout Abandon",
    type: "flow",
    category: "core",
    detailLevel: "full",
    priorityDefault: "high",
    trigger: "Known profile starts checkout and leaves without purchase.",
    flowFilters: [
      "Has not placed order since flow start",
      "Has email consent",
      "Suppress if checkout completed in another session",
    ],
    description: "Recover the highest-intent abandoners with checkout-specific reminders and friction removal.",
    objective: "Return shoppers to checkout and remove final purchase barriers.",
    targetAudience: "Checkout starters who did not complete purchase.",
    sequence: [
      {
        step: 1,
        name: "Checkout reminder",
        timing: "30-90 minutes after checkout start",
        objective: "Bring the shopper back before intent fades.",
        contentAngle: "Checkout resume link and concise reassurance.",
      },
      {
        step: 2,
        name: "Friction remover",
        timing: "12-24 hours after step 1",
        objective: "Address shipping, returns, payment, or product confidence.",
        contentAngle: "Policies, support, and confidence proof.",
      },
      {
        step: 3,
        name: "Final reminder",
        timing: "1-2 days after step 2",
        objective: "Give a final reason to complete purchase.",
        contentAngle: "Cart value, product benefits, and one checkout CTA.",
      },
    ],
    timing: ["30-90 minutes", "12-24 hours", "Day 2-3"],
    contentSuggestions: [
      "Use checkout resume links where possible.",
      "Prioritize clarity and trust over discovery.",
      "Keep copy short because intent is already high.",
    ],
    keyMetric: "checkout_recovery_revenue",
    offerRules: [
      "Escalate incentives carefully and only after non-discount reminders.",
      "Respect margin and brand discount policy.",
    ],
    qaRisks: [
      "Broken checkout links.",
      "Conflicting offer terms.",
      "Sending after purchase due to delayed event sync.",
    ],
    requiredData: ["started_checkout_event", "checkout_url", "checkout_items", "email_consent"],
    permissionLevel: "copilot",
    recommendedWhen: [
      "Checkout starts are available and abandoned checkout revenue matters.",
      "The brand can safely link shoppers back to checkout.",
    ],
    conditionalRequirements: ["Started Checkout and checkout URL data must be reliable."],
    plannerMatch: {
      aliases: ["checkout abandon", "checkout abandonment", "abandoned checkout", "checkout recovery"],
      triggerKeywords: ["started checkout", "checkout started", "checkout reminder"],
    },
  },
  {
    id: "replenishment",
    name: "Replenishment",
    type: "flow",
    category: "conditional",
    detailLevel: "full",
    priorityDefault: "conditional",
    trigger: "Customer is approaching expected product replenishment window.",
    flowFilters: [
      "Has purchased replenishable product",
      "Has not repurchased same product recently",
      "Has email consent",
    ],
    description: "Prompt customers to restock when timing and product cadence suggest real need.",
    objective: "Increase repeat purchase by reaching customers before they run out or switch.",
    targetAudience: "Previous buyers of replenishable products.",
    sequence: [
      {
        step: 1,
        name: "Restock reminder",
        timing: "5-10 days before expected runout",
        objective: "Create a timely restock prompt.",
        contentAngle: "Product cadence, benefit reminder, and easy reorder CTA.",
      },
      {
        step: 2,
        name: "Routine support",
        timing: "3-5 days after step 1",
        objective: "Help the customer stay consistent.",
        contentAngle: "Usage tips, routine education, and reorder CTA.",
      },
    ],
    timing: ["Before expected runout", "3-5 days later"],
    contentSuggestions: [
      "Use product-specific replenishment timing.",
      "Frame as helpful continuity, not pressure.",
      "Include reorder path and product benefit reminder.",
    ],
    keyMetric: "replenishment_repeat_rate",
    offerRules: [
      "Prefer convenience and timing over discounts.",
      "Use subscription or bundle nudges where available.",
    ],
    qaRisks: [
      "Incorrect replenishment window.",
      "Recommending restock after a recent purchase.",
      "Missing product-specific usage context.",
    ],
    requiredData: ["order_history", "product_replenishment_days", "last_purchase_date", "email_consent"],
    permissionLevel: "copilot",
    recommendedWhen: [
      "Products have real reorder or usage cadence.",
      "Product Performance Intelligence identifies replenishment candidates.",
    ],
    conditionalRequirements: ["Product cadence or repeat-purchase signals must support reorder timing."],
    plannerMatch: {
      aliases: ["replenishment", "restock", "reorder", "refill", "repeat purchase", "running low"],
      triggerKeywords: ["ordered product", "placed order", "expected runout", "replenishment date"],
    },
  },
  {
    id: "winback",
    name: "Winback",
    type: "flow",
    category: "core",
    detailLevel: "full",
    priorityDefault: "medium",
    trigger: "Customer passes expected repeat-purchase window or becomes at-risk/lapsed.",
    flowFilters: [
      "Has placed at least one prior order",
      "Has not placed order recently",
      "Has email consent",
      "Exclude active cart or checkout abandoners",
    ],
    description: "Re-engage lapsed or at-risk customers with value, proof, and a clear reason to return.",
    objective: "Recover customers before or after lapse without damaging deliverability or margin.",
    targetAudience: "At-risk, lapsed, or can't-lose customers.",
    sequence: [
      {
        step: 1,
        name: "Value reminder",
        timing: "At lapse threshold",
        objective: "Remind customers why they bought before.",
        contentAngle: "Product value, newness, best sellers, or routine support.",
      },
      {
        step: 2,
        name: "New reason to return",
        timing: "5-7 days after step 1",
        objective: "Create a current hook without relying only on price.",
        contentAngle: "New product, customer story, or improved experience.",
      },
      {
        step: 3,
        name: "Final reactivation",
        timing: "7-10 days after step 2",
        objective: "Make one final, controlled reactivation attempt.",
        contentAngle: "Best offer if allowed, preference center, or stay-in-touch CTA.",
      },
    ],
    timing: ["At lapse threshold", "5-7 days later", "7-10 days later"],
    contentSuggestions: [
      "Segment by value and engagement before volume ramping.",
      "Use product value and newness before incentives.",
      "Keep frequency controlled for colder cohorts.",
    ],
    keyMetric: "reactivation_revenue",
    offerRules: [
      "Use incentives only for segments where promo responsiveness or margin supports it.",
      "Avoid sending aggressive offers to refund-prone or cold profiles.",
    ],
    qaRisks: [
      "Over-mailing cold cohorts.",
      "Spammy urgency language.",
      "Discounting customers who would return without an offer.",
    ],
    requiredData: ["order_history", "last_purchase_date", "customer_segment", "email_consent"],
    permissionLevel: "copilot",
    recommendedWhen: [
      "Repeat purchase cycles exist and customers lapse.",
      "The brand has enough historical buyers to segment reactivation.",
    ],
    conditionalRequirements: ["Last purchase date and lapse thresholds must be reliable."],
    plannerMatch: {
      aliases: ["winback", "win back", "reactivation", "lapsed customer", "at risk", "churn recovery"],
      triggerKeywords: ["lapsed", "reactivate", "at risk", "churn", "no purchase"],
    },
  },
  {
    id: "collection_abandon",
    name: "Collection Abandon",
    type: "flow",
    category: "secondary",
    detailLevel: "partial",
    priorityDefault: "low",
    trigger: "Known profile views a collection/category page and leaves without product view, cart, checkout, or purchase.",
    flowFilters: [
      "Has not viewed product since flow start",
      "Has not added to cart since flow start",
      "Has not placed order since flow start",
      "Has email consent",
    ],
    description: "Recover category-level interest when intent is broader than a specific product.",
    objective: "Guide category browsers to best sellers, product education, or fit guidance.",
    targetAudience: "Known browsers with collection/category interest but no product-level action.",
    sequence: [
      {
        step: 1,
        name: "Category guide",
        timing: "4-8 hours after collection view",
        objective: "Help the shopper narrow the collection.",
        contentAngle: "Best sellers, fit guide, quiz, or category education.",
      },
      {
        step: 2,
        name: "Proof by category",
        timing: "1 day after step 1",
        objective: "Reduce uncertainty around the category.",
        contentAngle: "Reviews, UGC, buying guide, or comparison.",
      },
    ],
    timing: ["4-8 hours", "Day 1"],
    contentSuggestions: [
      "Use category-level education rather than pretending product intent is known.",
      "Feature a small set of proven products from the collection.",
    ],
    keyMetric: "collection_recovery_revenue",
    offerRules: ["Avoid discounts unless collection recovery is proven and margin supports it."],
    qaRisks: [
      "Over-personalizing a broad browse signal.",
      "Broken dynamic collection links.",
      "Conflicting with product-level browse abandon logic.",
    ],
    requiredData: ["viewed_collection_event", "collection_catalog", "email_consent"],
    permissionLevel: "copilot",
    recommendedWhen: [
      "Collection/category browsing is tracked distinctly from product views.",
      "Collections are meaningful shopping paths.",
    ],
    conditionalRequirements: ["Viewed Collection or equivalent collection-level event must exist."],
    plannerMatch: {
      aliases: ["collection abandon", "collection abandonment", "category abandon", "category browse"],
      triggerKeywords: ["viewed collection", "collection viewed", "viewed category", "category viewed"],
    },
  },
  {
    id: "cross_sell",
    name: "Cross-Sell",
    type: "flow",
    category: "secondary",
    detailLevel: "full",
    priorityDefault: "medium",
    trigger: "Customer purchases a product that has a logical companion, add-on, refill, or next-best product.",
    flowFilters: [
      "Has placed order",
      "Has not purchased recommended companion product",
      "Has email consent",
    ],
    description: "Recommend complementary products after a purchase or lifecycle milestone.",
    objective: "Increase second purchase rate and attach-rate without confusing the original purchase experience.",
    targetAudience: "Recent buyers with clear companion-product opportunities.",
    sequence: [
      {
        step: 1,
        name: "Companion recommendation",
        timing: "3-10 days after purchase or delivery",
        objective: "Introduce the most relevant companion product.",
        contentAngle: "How the add-on improves the original product or routine.",
      },
      {
        step: 2,
        name: "Use-case proof",
        timing: "5-7 days after step 1",
        objective: "Show why the companion product belongs in the customer's routine.",
        contentAngle: "Usage tips, bundle logic, UGC, or reviews.",
      },
    ],
    timing: ["3-10 days after purchase/delivery", "5-7 days later"],
    contentSuggestions: [
      "Base recommendations on product truth, not generic best sellers.",
      "Explain the relationship between the purchased product and the suggested product.",
    ],
    keyMetric: "cross_sell_conversion_rate",
    offerRules: [
      "Bundle or add-on incentives can work when margin supports them.",
      "Avoid recommending items the customer already bought recently.",
    ],
    qaRisks: [
      "Irrelevant product pairing.",
      "Sending before the original order has arrived.",
      "Conflicting with replenishment or subscription timing.",
    ],
    requiredData: ["order_history", "product_catalog", "product_affinity", "email_consent"],
    permissionLevel: "copilot",
    recommendedWhen: [
      "Product Performance Intelligence identifies add-on boosters or revenue anchors.",
      "The catalog has natural pairings, kits, accessories, or routine steps.",
    ],
    conditionalRequirements: ["Product affinity or merchandised pairing logic should exist."],
    plannerMatch: {
      aliases: ["cross sell", "cross-sell", "companion product", "add on", "addon", "next best product"],
      triggerKeywords: ["placed order", "ordered product", "fulfilled order"],
    },
  },
  {
    id: "post_purchase_pre_delivery",
    name: "Post-Purchase Pre-Delivery",
    type: "flow",
    category: "secondary",
    detailLevel: "full",
    priorityDefault: "medium",
    trigger: "Customer places an order and is waiting for delivery or fulfillment.",
    flowFilters: [
      "Has placed order",
      "Order has not been delivered",
      "Exclude transactional messages that must stay operational",
    ],
    description: "Reduce buyer anxiety and prepare the customer before the product arrives.",
    objective: "Improve post-purchase confidence, reduce support friction, and prime product usage.",
    targetAudience: "Recent purchasers before delivery.",
    sequence: [
      {
        step: 1,
        name: "Order confidence",
        timing: "Immediately to 1 day after purchase",
        objective: "Confirm what happens next and reduce uncertainty.",
        contentAngle: "Expectation setting, support path, and brand reassurance.",
      },
      {
        step: 2,
        name: "Prepare to use",
        timing: "Before expected delivery",
        objective: "Help the customer get more value from the purchase.",
        contentAngle: "How to prepare, setup tips, sizing, storage, or routine guidance.",
      },
    ],
    timing: ["Immediately to Day 1", "Before delivery"],
    contentSuggestions: [
      "Separate operational order updates from brand education.",
      "Use product-specific guidance when available.",
    ],
    keyMetric: "post_purchase_engagement_rate",
    offerRules: ["Avoid aggressive selling before the first order arrives."],
    qaRisks: [
      "Duplicating transactional emails.",
      "Sending inaccurate delivery expectations.",
      "Adding pressure before the customer experiences the product.",
    ],
    requiredData: ["order_created_event", "fulfillment_status", "expected_delivery_date"],
    permissionLevel: "copilot",
    recommendedWhen: [
      "Shipping windows create customer anxiety or setup needs.",
      "Products benefit from pre-delivery education.",
    ],
    conditionalRequirements: ["Order and fulfillment status should be available or timing must be conservative."],
    plannerMatch: {
      aliases: ["post purchase pre delivery", "pre delivery", "post-purchase pre-delivery", "before delivery", "order education"],
      triggerKeywords: ["placed order", "order created", "order confirmation", "fulfillment"],
    },
  },
  {
    id: "post_purchase_post_delivery",
    name: "Post-Purchase Post-Delivery",
    type: "flow",
    category: "secondary",
    detailLevel: "full",
    priorityDefault: "medium",
    trigger: "Customer's order is delivered or enough time has passed for first product usage.",
    flowFilters: [
      "Has received order or reached conservative delivery window",
      "Has not requested refund",
      "Has email consent where marketing content is included",
    ],
    description: "Help customers use the product successfully after delivery and open the door to repeat purchase.",
    objective: "Increase satisfaction, product adoption, review readiness, and second-purchase momentum.",
    targetAudience: "Recent buyers after delivery or first-use window.",
    sequence: [
      {
        step: 1,
        name: "First-use support",
        timing: "1-3 days after delivery",
        objective: "Help the customer get value from the purchase.",
        contentAngle: "Usage tips, care instructions, routine guidance, or setup.",
      },
      {
        step: 2,
        name: "Outcome reinforcement",
        timing: "5-10 days after step 1",
        objective: "Reinforce product value and reduce remorse.",
        contentAngle: "How to get better results, community proof, or troubleshooting.",
      },
    ],
    timing: ["1-3 days after delivery", "5-10 days later"],
    contentSuggestions: [
      "Lead with product success before asking for a review or another purchase.",
      "Use product-specific content where available.",
    ],
    keyMetric: "second_purchase_rate",
    offerRules: [
      "Avoid discounting too early after the first purchase.",
      "Use cross-sell only after value and usage context are clear.",
    ],
    qaRisks: [
      "Sending before delivery.",
      "Making unsupported product outcome claims.",
      "Asking for a review before use is plausible.",
    ],
    requiredData: ["delivery_status", "order_history", "product_catalog", "email_consent"],
    permissionLevel: "copilot",
    recommendedWhen: [
      "Products have onboarding, usage, care, or results education.",
      "Second purchase or review readiness is a retention priority.",
    ],
    conditionalRequirements: ["Delivery status or conservative delivery timing must be available."],
    plannerMatch: {
      aliases: ["post purchase post delivery", "post-delivery", "after delivery", "product education", "first use"],
      triggerKeywords: ["delivered", "fulfilled", "shipment delivered", "order delivered"],
    },
  },
  {
    id: "transactional",
    name: "Transactional Optimization",
    type: "flow",
    category: "infrastructure",
    detailLevel: "partial",
    priorityDefault: "conditional",
    trigger: "Order, shipping, delivery, refund, or account event that requires operational communication.",
    flowFilters: [
      "Use only for operationally appropriate audiences",
      "Do not suppress legally or operationally required messages",
      "Keep marketing content compliant and secondary",
    ],
    description: "Audit and optimize transactional messages for clarity, trust, and lifecycle handoff.",
    objective: "Improve operational clarity and route customers into the right retention path after the transaction.",
    targetAudience: "Customers receiving order, shipping, delivery, return, or account updates.",
    sequence: [
      {
        step: 1,
        name: "Operational clarity",
        timing: "At the transactional event",
        objective: "Make the required update clear and easy to act on.",
        contentAngle: "Order details, shipping status, support path, and next step.",
      },
    ],
    timing: ["At event time"],
    contentSuggestions: [
      "Prioritize the operational message over marketing content.",
      "Use transactional messages as lifecycle handoff points only where compliant.",
    ],
    keyMetric: "transactional_engagement_rate",
    offerRules: ["Do not add promotional language where transactional rules disallow it."],
    qaRisks: [
      "Mixing promotional content into restricted transactional sends.",
      "Confusing order status or tracking links.",
      "Duplicate operational messages from Shopify/Klaviyo.",
    ],
    requiredData: ["order_status", "shipping_status", "tracking_url", "transactional_permission_basis"],
    permissionLevel: "manual",
    recommendedWhen: [
      "Order tracking, shipping, or delivery data exists.",
      "The brand needs operational email clarity or lifecycle handoff review.",
    ],
    conditionalRequirements: ["Order tracking or transactional event data must exist before optimization is recommended strongly."],
    plannerMatch: {
      aliases: ["transactional", "order confirmation", "shipping confirmation", "delivery update", "tracking update"],
      triggerKeywords: ["fulfilled order", "shipment", "tracking", "refund", "return"],
    },
  },
  {
    id: "back_in_stock",
    name: "Back in Stock",
    type: "flow",
    category: "conditional",
    detailLevel: "full",
    priorityDefault: "conditional",
    trigger: "A subscribed shopper is notified when an out-of-stock product becomes available.",
    flowFilters: [
      "Subscribed to back-in-stock alert",
      "Product is available",
      "Has not purchased the product recently",
    ],
    description: "Convert explicit product demand when inventory returns.",
    objective: "Recover high-intent demand captured while products were unavailable.",
    targetAudience: "Profiles subscribed to back-in-stock alerts or waitlists.",
    sequence: [
      {
        step: 1,
        name: "Availability alert",
        timing: "Immediately when product returns",
        objective: "Notify the shopper while demand is fresh.",
        contentAngle: "Product is back, clear CTA, and honest availability framing.",
      },
      {
        step: 2,
        name: "Reminder if still available",
        timing: "12-24 hours later",
        objective: "Give a final helpful reminder if inventory remains.",
        contentAngle: "Proof, product value, and stock-aware urgency.",
      },
    ],
    timing: ["Immediately", "12-24 hours later if still available"],
    contentSuggestions: [
      "Keep product and availability details accurate.",
      "Avoid urgency unless inventory really is constrained.",
    ],
    keyMetric: "back_in_stock_revenue",
    offerRules: ["Do not discount by default; demand is already explicit."],
    qaRisks: [
      "Sending after inventory sells out.",
      "Broken product links.",
      "Overstating scarcity.",
    ],
    requiredData: ["back_in_stock_subscription", "inventory_status", "product_catalog", "email_or_sms_consent"],
    permissionLevel: "copilot",
    recommendedWhen: [
      "Products frequently sell out and shoppers subscribe to alerts.",
      "Inventory return events sync into Klaviyo.",
    ],
    conditionalRequirements: ["Back-in-stock subscription and inventory availability events must exist."],
    plannerMatch: {
      aliases: ["back in stock", "back-in-stock", "restock alert", "waitlist", "notify me"],
      triggerKeywords: ["back in stock", "inventory replenished", "subscribed to back in stock"],
    },
  },
  {
    id: "review",
    name: "Review Request",
    type: "flow",
    category: "secondary",
    detailLevel: "full",
    priorityDefault: "medium",
    trigger: "Customer has had enough time to use the delivered product.",
    flowFilters: [
      "Order delivered or conservative usage window passed",
      "Has not already reviewed the product",
      "Exclude refund or support-risk cases where available",
    ],
    description: "Ask for a review after the customer has plausibly experienced the product.",
    objective: "Grow review volume and product proof without harming customer experience.",
    targetAudience: "Recent buyers after delivery and first-use window.",
    sequence: [
      {
        step: 1,
        name: "Review ask",
        timing: "7-21 days after delivery depending on product use cycle",
        objective: "Ask for honest product feedback at the right moment.",
        contentAngle: "Simple review CTA, appreciation, and product-specific context.",
      },
      {
        step: 2,
        name: "Gentle reminder",
        timing: "5-7 days later",
        objective: "Give a second chance without pestering.",
        contentAngle: "Community proof, value of feedback, and one CTA.",
      },
    ],
    timing: ["7-21 days after delivery", "5-7 days later"],
    contentSuggestions: [
      "Time the ask by product usage cycle.",
      "Keep the ask simple and low-friction.",
    ],
    keyMetric: "review_submission_rate",
    offerRules: [
      "Only incentivize reviews where policy and platform rules allow it.",
      "Do not require positive reviews for incentives.",
    ],
    qaRisks: [
      "Asking before delivery or use.",
      "Violating review platform incentive rules.",
      "Sending to customers with unresolved support issues.",
    ],
    requiredData: ["delivery_status", "review_platform_status", "product_usage_window"],
    permissionLevel: "copilot",
    recommendedWhen: [
      "Reviews are important for product proof.",
      "A review platform or review capture path exists.",
    ],
    conditionalRequirements: ["Review capture destination and delivery/usage timing should exist."],
    plannerMatch: {
      aliases: ["review", "review request", "product review", "request a review", "leave a review"],
      triggerKeywords: ["delivered", "fulfilled", "review submitted", "product review"],
    },
  },
  {
    id: "sunset",
    name: "Sunset",
    type: "flow",
    category: "secondary",
    detailLevel: "partial",
    priorityDefault: "medium",
    trigger: "Profile has been unengaged for a defined period and should be re-permissioned or suppressed.",
    flowFilters: [
      "No opens/clicks for defined period",
      "No recent purchase or high-value exception",
      "Has email consent",
    ],
    description: "Protect deliverability by giving cold subscribers a final choice before suppression or reduced frequency.",
    objective: "Reduce list risk while preserving customers who still want to hear from the brand.",
    targetAudience: "Cold, unengaged subscribers or deliverability-risk cohorts.",
    sequence: [
      {
        step: 1,
        name: "Stay subscribed prompt",
        timing: "At unengaged threshold",
        objective: "Confirm whether the subscriber still wants messages.",
        contentAngle: "Preference center, value reminder, and clear stay/leave path.",
      },
      {
        step: 2,
        name: "Final permission check",
        timing: "5-7 days later",
        objective: "Make one final low-pressure re-permission attempt.",
        contentAngle: "Simple opt-in CTA or unsubscribe/preference clarity.",
      },
    ],
    timing: ["At unengaged threshold", "5-7 days later"],
    contentSuggestions: [
      "Make preferences clear.",
      "Avoid aggressive selling to cold subscribers.",
    ],
    keyMetric: "deliverability_risk_reduction",
    offerRules: ["Avoid using deep discounts as the default sunset tactic."],
    qaRisks: [
      "Mailing too many cold profiles.",
      "Suppressing recent purchasers by mistake.",
      "Confusing unsubscribe or preference language.",
    ],
    requiredData: ["engagement_history", "last_open_or_click_date", "purchase_history", "suppression_policy"],
    permissionLevel: "manual",
    recommendedWhen: [
      "The list has large cold cohorts or deliverability risk.",
      "The brand has a suppression or re-permission policy.",
    ],
    conditionalRequirements: ["Engagement recency and suppression rules must be reliable."],
    plannerMatch: {
      aliases: ["sunset", "sunset flow", "repermission", "re-permission", "inactive subscriber", "list cleaning"],
      triggerKeywords: ["unengaged", "inactive", "no opens", "no clicks", "suppress"],
    },
  },
  {
    id: "price_drop",
    name: "Price Drop",
    type: "flow",
    category: "conditional",
    detailLevel: "partial",
    priorityDefault: "conditional",
    trigger: "A viewed, wishlisted, or subscribed product drops in price.",
    flowFilters: [
      "Profile showed interest in the product",
      "Product price dropped",
      "Has not purchased product recently",
      "Has email consent",
    ],
    description: "Notify interested shoppers when a product they considered becomes less expensive.",
    objective: "Convert price-sensitive demand without training all shoppers to wait for markdowns.",
    targetAudience: "Known product considerers with price-drop relevance.",
    sequence: [
      {
        step: 1,
        name: "Price drop alert",
        timing: "Soon after price drop",
        objective: "Notify interested shoppers of a real price change.",
        contentAngle: "Product reminder, new price context, and clear CTA.",
      },
    ],
    timing: ["Soon after price drop"],
    contentSuggestions: [
      "Use only truthful price changes.",
      "Keep the message product-specific.",
    ],
    keyMetric: "price_drop_revenue",
    offerRules: ["Use only when markdown strategy intentionally supports price-drop messaging."],
    qaRisks: [
      "Training customers to wait for discounts.",
      "Incorrect price rendering.",
      "Sending after the price changes again.",
    ],
    requiredData: ["price_history", "product_interest_event", "product_catalog", "email_consent"],
    permissionLevel: "copilot",
    recommendedWhen: [
      "Price drops are part of the merchandising strategy.",
      "Product-level interest and price-history data exist.",
    ],
    conditionalRequirements: ["Price-drop strategy and price history data must exist."],
    plannerMatch: {
      aliases: ["price drop", "price-drop", "markdown alert", "sale alert", "wishlist price drop"],
      triggerKeywords: ["price dropped", "product price", "discounted product"],
    },
  },
  {
    id: "low_inventory",
    name: "Low Inventory",
    type: "flow",
    category: "conditional",
    detailLevel: "partial",
    priorityDefault: "conditional",
    trigger: "A product with known shopper interest reaches a real low-inventory threshold.",
    flowFilters: [
      "Profile showed product interest",
      "Product inventory is below threshold",
      "Has not purchased product recently",
      "Has email consent",
    ],
    description: "Use real inventory scarcity to help interested shoppers decide before stock runs out.",
    objective: "Convert product considerers when inventory risk is genuine.",
    targetAudience: "Known product considerers for low-stock products.",
    sequence: [
      {
        step: 1,
        name: "Low-stock alert",
        timing: "When inventory threshold is reached",
        objective: "Communicate a truthful urgency signal.",
        contentAngle: "Product interest reminder, stock context, and one CTA.",
      },
    ],
    timing: ["At low-inventory threshold"],
    contentSuggestions: [
      "Use precise urgency only when inventory data supports it.",
      "Avoid low-stock language for evergreen inventory.",
    ],
    keyMetric: "low_inventory_conversion_rate",
    offerRules: ["Avoid extra discounts when scarcity is the conversion reason."],
    qaRisks: [
      "False scarcity.",
      "Inventory sync lag.",
      "Sending after stockout.",
    ],
    requiredData: ["inventory_quantity", "inventory_threshold", "product_interest_event", "email_consent"],
    permissionLevel: "copilot",
    recommendedWhen: [
      "Inventory scarcity is real and customer-friendly to communicate.",
      "Product interest and inventory data sync reliably.",
    ],
    conditionalRequirements: ["Reliable inventory thresholds and product-interest data must exist."],
    plannerMatch: {
      aliases: ["low inventory", "low stock", "almost gone", "stock alert", "inventory alert"],
      triggerKeywords: ["inventory", "low stock", "stock threshold", "almost sold out"],
    },
  },
  {
    id: "birthday",
    name: "Birthday",
    type: "flow",
    category: "conditional",
    detailLevel: "full",
    priorityDefault: "conditional",
    trigger: "Customer birthday or birth month is known and permission allows celebration messaging.",
    flowFilters: [
      "Birthday or birth month exists",
      "Has email or SMS consent",
      "Suppress if offer already redeemed",
    ],
    description: "Celebrate customers with a relevant birthday moment when first-party birthday data exists.",
    objective: "Drive goodwill and incremental purchase from a personal lifecycle moment.",
    targetAudience: "Customers or subscribers with birthday data.",
    sequence: [
      {
        step: 1,
        name: "Birthday treat",
        timing: "At birthday or start of birth month",
        objective: "Celebrate the customer and present a relevant perk if allowed.",
        contentAngle: "Warm birthday note, curated picks, or birthday offer.",
      },
      {
        step: 2,
        name: "Birthday reminder",
        timing: "Before birthday window closes",
        objective: "Remind the customer before the perk expires.",
        contentAngle: "Friendly reminder and one CTA.",
      },
    ],
    timing: ["Birthday/birth month start", "Before window closes"],
    contentSuggestions: [
      "Use a celebratory tone without over-personalizing.",
      "Make offer terms clear if an offer is used.",
    ],
    keyMetric: "birthday_revenue",
    offerRules: [
      "Use a birthday-specific perk only if brand policy and margin allow.",
      "Avoid generic discounting when birthday data is sparse.",
    ],
    qaRisks: [
      "Missing or inaccurate birthday data.",
      "Unclear expiration terms.",
      "Sending to profiles without consent.",
    ],
    requiredData: ["birthday", "email_or_sms_consent", "offer_redemption_status"],
    permissionLevel: "copilot",
    recommendedWhen: [
      "Birthday or birth month data exists at meaningful coverage.",
      "The brand has a birthday perk or birthday content strategy.",
    ],
    conditionalRequirements: ["Birthday data must exist before this is strongly recommended."],
    plannerMatch: {
      aliases: ["birthday", "birth month", "birthday flow", "birthday reward", "birthday offer"],
      triggerKeywords: ["birthday", "birthdate", "date property", "anniversary"],
    },
  },
  {
    id: "loyalty",
    name: "Loyalty",
    type: "flow",
    category: "conditional",
    detailLevel: "partial",
    priorityDefault: "conditional",
    trigger: "Customer joins, earns, redeems, approaches a tier, or risks losing loyalty value.",
    flowFilters: [
      "Has loyalty profile or points balance",
      "Event matches loyalty milestone",
      "Has email or SMS consent where required",
    ],
    description: "Use loyalty milestones to increase repeat purchase, redemption, and tier engagement.",
    objective: "Turn loyalty program signals into clear next actions for customers.",
    targetAudience: "Loyalty members or customers eligible for loyalty milestones.",
    sequence: [
      {
        step: 1,
        name: "Loyalty milestone",
        timing: "At loyalty event or threshold",
        objective: "Tell the customer what changed and what to do next.",
        contentAngle: "Points balance, tier progress, reward availability, or next purchase path.",
      },
    ],
    timing: ["At loyalty event", "Reminder based on expiration or tier timing"],
    contentSuggestions: [
      "Make loyalty value concrete.",
      "Use clear math for points, tiers, and rewards.",
    ],
    keyMetric: "loyalty_repeat_rate",
    offerRules: ["Respect loyalty program terms and expiration rules."],
    qaRisks: [
      "Incorrect points balance.",
      "Confusing tier logic.",
      "Sending loyalty messages to non-members.",
    ],
    requiredData: ["loyalty_program_status", "points_balance", "tier_status", "reward_expiration"],
    permissionLevel: "copilot",
    recommendedWhen: [
      "A loyalty program exists.",
      "Loyalty events or profile properties sync into Klaviyo.",
    ],
    conditionalRequirements: ["A loyalty program and loyalty data sync must exist."],
    plannerMatch: {
      aliases: ["loyalty", "rewards", "points", "vip tier", "loyalty program", "reward reminder"],
      triggerKeywords: ["points", "reward", "tier", "loyalty"],
    },
  },
  {
    id: "subscription",
    name: "Subscription",
    type: "flow",
    category: "conditional",
    detailLevel: "partial",
    priorityDefault: "conditional",
    trigger: "Subscription lifecycle event such as start, renewal, skip, cancellation risk, failed payment, or membership milestone.",
    flowFilters: [
      "Has active or relevant subscription status",
      "Event matches subscription milestone",
      "Suppress if status changes before send",
    ],
    description: "Support subscribers through onboarding, renewal, skipped orders, failed payments, and cancellation risk.",
    objective: "Increase subscription retention and reduce avoidable churn.",
    targetAudience: "Subscribers, members, or customers with subscription lifecycle events.",
    sequence: [
      {
        step: 1,
        name: "Subscription milestone",
        timing: "At subscription event",
        objective: "Clarify the customer's subscription status and next step.",
        contentAngle: "Renewal reminder, skip/save options, failed payment help, or member benefit.",
      },
      {
        step: 2,
        name: "Retention support",
        timing: "Based on renewal or cancellation-risk timing",
        objective: "Reduce churn with value, flexibility, and support.",
        contentAngle: "Routine value, account management, benefit reminder, or save path.",
      },
    ],
    timing: ["At subscription event", "Before renewal or after risk event"],
    contentSuggestions: [
      "Prioritize account clarity and flexibility.",
      "Use save offers carefully and segment by churn risk.",
    ],
    keyMetric: "subscription_retention_rate",
    offerRules: ["Use subscription incentives only within program and margin rules."],
    qaRisks: [
      "Incorrect subscription status.",
      "Sending after cancellation or renewal state changed.",
      "Confusing account-management CTAs.",
    ],
    requiredData: ["subscription_status", "renewal_date", "payment_status", "membership_status"],
    permissionLevel: "copilot",
    recommendedWhen: [
      "Subscriptions, memberships, or recurring orders exist.",
      "Subscription lifecycle events sync into Klaviyo.",
    ],
    conditionalRequirements: ["Subscription or membership business model and event data must exist."],
    plannerMatch: {
      aliases: ["subscription", "membership", "subscriber renewal", "renewal", "failed payment", "dunning"],
      triggerKeywords: ["subscription", "renewal", "cancelled subscription", "skipped subscription", "payment failed"],
    },
  },
  {
    id: "cdp_aa",
    name: "CDP Audience Automation",
    type: "flow",
    category: "infrastructure",
    detailLevel: "placeholder",
    priorityDefault: "conditional",
    trigger: "Audience, segment, or CDP property automation updates lifecycle eligibility or suppressions.",
    flowFilters: [
      "No customer-facing message required by default",
      "Validate segment membership and property updates",
      "Keep suppression and eligibility rules documented",
    ],
    description: "Infrastructure automation for lifecycle audiences, customer properties, and suppression logic.",
    objective: "Keep lifecycle targeting, suppression, and customer-state logic durable and auditable.",
    targetAudience: "Internal audience automation, segment syncs, and customer-state workflows.",
    sequence: [],
    timing: ["Triggered by audience or property update"],
    contentSuggestions: [
      "Do not treat CDP/audience automation as a normal message flow.",
      "Document inputs, outputs, and downstream lifecycle dependencies.",
    ],
    keyMetric: "audience_automation_accuracy",
    offerRules: ["No offer logic by default; this is infrastructure."],
    qaRisks: [
      "Mistaking audience automation for a customer-facing message flow.",
      "Breaking downstream suppressions or eligibility.",
      "Overclaiming audit coverage without segment/property details.",
    ],
    requiredData: ["segment_definitions", "profile_properties", "suppression_rules", "audience_sync_status"],
    permissionLevel: "manual",
    recommendedWhen: [
      "The brand uses CDP, audience automation, or lifecycle property workflows.",
      "Retention flows depend on shared segments, suppressions, or customer-state properties.",
    ],
    conditionalRequirements: ["CDP/audience automation architecture must exist before this is recommended strongly."],
    plannerMatch: {
      aliases: ["cdp", "audience automation", "cdp aa", "segment automation", "profile property automation"],
      triggerKeywords: ["segment", "profile property", "audience", "suppression", "cdp"],
    },
  },
];

export function isCoreRequiredFlowPlaybook(playbook: FlowPlaybook) {
  return playbook.category === "core" && CORE_REQUIRED_FLOW_PLAYBOOK_IDS.includes(
    playbook.id as (typeof CORE_REQUIRED_FLOW_PLAYBOOK_IDS)[number],
  );
}

export function flowPlaybooksByCategory(category: FlowPlaybook["category"]) {
  return flowPlaybooks.filter((playbook) => playbook.category === category);
}
